/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/test-gltf-scene.gltf");
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                geometry={nodes.ground_shiny.geometry}
                material={materials.metallic_reflect}
            />
            <mesh
                geometry={nodes.box1.geometry}
                material={nodes.box1.material}
            />
            <mesh
                geometry={nodes.top_ring_light.geometry}
                material={materials.emis}
            />
        </group>
    );
}

useGLTF.preload("/test-gltf-scene.gltf");
